datazone:
  tfe_workspace: retail_payments_datazone_ws
  datazone_domain_name: "retail_payments"
  datazone_description: "RBS Payments Datazone"
  datazone_kms_key_identifier: null
  single_sign_on: {}
  tags: null
  region: "ap-southeast-2"
  environment_blueprints:
    DefaultDataWarehouse:
      enabled_regions: ["ap-southeast-2"]
      environment_blueprint_identifier: "DefaultDataWarehouse"
    DefaultDataLake:
      enabled_regions: ["ap-southeast-2"]
      environment_blueprint_identifier: "DefaultDataLake"
  datazone_projects:
    rbs_payments_raw:
      description: "rbs payments raw"
      glossary_terms: ["example"]
    rbs_payments_curated:
      description: "rbs payments curated"
      glossary_terms: ["example"]
    rbs_payments_product:
      description: "rbs payments product"
      glossary_terms: ["example"]
redshift:
datazone_environments:
  tfe_workspace: retail_payments_datazone_env_ws
  datazone_workspace_name: "retail_payments_datazone_ws"
  datazone_environment_profiles:
    DefaultDataLake:
      aws_account_id: "855831148133"
      name: "DataLake_profile"
      region: "ap-southeast-2"
      environment_blueprint_identifier: "DefaultDataLake"
      project_identifier: "shared_env"
  datazone_environments:
    Raw:
      name: "payments_datalake_raw"
      environment_profile_identifier: "DefaultDataLake"
      project_identifier: "rbs_payments_raw"
    Curated:
      name: "payments_datalake_curated"
      environment_profile_identifier: "DefaultDataLake"
      project_identifier: "rbs_payments_curated"
    Product:
      name: "payments_datalake+product"
      environment_profile_identifier: "DefaultDataLake"
      project_identifier: "rbs_payments_product"
